# Site settings
title: 3Dprnbls
email: vetalik@gmail.com
description: This small blog is the place to collect usefull stuff i print."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
