# Site settings
title: 3DPrintables
email: vetalik@gmail.com
description: "This is small blog for sharing 3D printing expirience, interesting stuff etc"
baseurl: ""
url: "http://kilatev.github.io/3Dprtbls"

# Build settings
markdown: kramdown
permalink: pretty

pygments: true
